export interface ChildCategory {
  id: string;
  name: string;
  slug: string;
  description: string;
  parentId: string;
  parentName: string;
  courseCount: number;
  articleCount: number;
  icon: string;
  color: string;
  status: 'Active' | 'Draft' | 'Archived';
  createdAt: string;
}

export interface ParentCategory {
  id: string;
  name: string;
  slug: string;
  description: string;
  icon: string;
  color: string;
  courseCount: number;
  articleCount: number;
  status: 'Active' | 'Draft' | 'Archived';
  children: ChildCategory[];
  createdAt: string;
}

export const MOCK_CATEGORIES: ParentCategory[] = [
  {
    id: 'cat-1',
    name: 'Artificial Intelligence & Machine Learning',
    slug: 'ai-ml',
    description: 'Foundations of mathematical modeling, supervised & unsupervised learning, deep neural networks and cognitive architectures.',
    icon: 'Brain',
    color: '#8b5cf6',
    courseCount: 18,
    articleCount: 42,
    status: 'Active',
    createdAt: 'Jan 15, 2026',
    children: [
      {
        id: 'sub-101',
        name: 'Deep Neural Networks & Backpropagation',
        slug: 'deep-neural-networks',
        description: 'Multi-layer perceptrons, matrix calculus, activation functions, loss surfaces, and gradient descent optimization.',
        parentId: 'cat-1',
        parentName: 'Artificial Intelligence & Machine Learning',
        courseCount: 6,
        articleCount: 14,
        icon: 'Network',
        color: '#8b5cf6',
        status: 'Active',
        createdAt: 'Jan 16, 2026',
      },
      {
        id: 'sub-102',
        name: 'Convolutional Neural Networks (CNN) & Vision',
        slug: 'cnn-computer-vision',
        description: 'Image feature extraction, pooling, YOLOv11 object detection, semantic segmentation, and Vision Transformers (ViT).',
        parentId: 'cat-1',
        parentName: 'Artificial Intelligence & Machine Learning',
        courseCount: 4,
        articleCount: 10,
        icon: 'Eye',
        color: '#3b82f6',
        status: 'Active',
        createdAt: 'Jan 18, 2026',
      },
      {
        id: 'sub-103',
        name: 'Reinforcement Learning (RL) & Policy Gradients',
        slug: 'reinforcement-learning',
        description: 'Markov decision processes (MDP), Q-Learning, PPO, Deep Q-Networks (DQN), and RLHF alignment for foundation models.',
        parentId: 'cat-1',
        parentName: 'Artificial Intelligence & Machine Learning',
        courseCount: 5,
        articleCount: 11,
        icon: 'Gamepad2',
        color: '#ec4899',
        status: 'Active',
        createdAt: 'Jan 20, 2026',
      },
      {
        id: 'sub-104',
        name: 'Probabilistic Graphical Models & Bayesian ML',
        slug: 'bayesian-ml',
        description: 'Bayesian networks, Markov Random Fields, variational inference, and uncertainty quantification in neural nets.',
        parentId: 'cat-1',
        parentName: 'Artificial Intelligence & Machine Learning',
        courseCount: 3,
        articleCount: 7,
        icon: 'Binary',
        color: '#06b6d4',
        status: 'Active',
        createdAt: 'Jan 22, 2026',
      },
    ],
  },
  {
    id: 'cat-2',
    name: 'Generative AI & Large Language Models',
    slug: 'generative-ai-llms',
    description: 'Transformer architectures, multi-head attention, self-attention mechanisms, reasoning models, and agentic workflows.',
    icon: 'Sparkles',
    color: '#ec4899',
    courseCount: 24,
    articleCount: 68,
    status: 'Active',
    createdAt: 'Feb 01, 2026',
    children: [
      {
        id: 'sub-201',
        name: 'Attention Mechanisms & Transformer Engineering',
        slug: 'transformer-engineering',
        description: 'Scales Dot-Product Attention, Query-Key-Value projections, RoPE embeddings, FlashAttention-3, and KV caching.',
        parentId: 'cat-2',
        parentName: 'Generative AI & Large Language Models',
        courseCount: 8,
        articleCount: 22,
        icon: 'Cpu',
        color: '#ec4899',
        status: 'Active',
        createdAt: 'Feb 02, 2026',
      },
      {
        id: 'sub-202',
        name: 'Retrieval-Augmented Generation (RAG) & Vector Databases',
        slug: 'rag-vector-databases',
        description: 'Dense embedding models, HNSW indexing, hybrid BM25 + vector search, GraphRAG, reranking, and semantic chunking.',
        parentId: 'cat-2',
        parentName: 'Generative AI & Large Language Models',
        courseCount: 7,
        articleCount: 19,
        icon: 'Database',
        color: '#10b981',
        status: 'Active',
        createdAt: 'Feb 04, 2026',
      },
      {
        id: 'sub-203',
        name: 'Autonomous Multi-Agent Swarms & LangGraph',
        slug: 'multi-agent-swarms',
        description: 'Hierarchical agent orchestration, reflection loops, dynamic tool calling, memory stores, and task DAG execution.',
        parentId: 'cat-2',
        parentName: 'Generative AI & Large Language Models',
        courseCount: 5,
        articleCount: 16,
        icon: 'Bot',
        color: '#8b5cf6',
        status: 'Active',
        createdAt: 'Feb 06, 2026',
      },
      {
        id: 'sub-204',
        name: 'Fine-Tuning, LoRA, QLoRA & Distillation',
        slug: 'fine-tuning-lora',
        description: 'Low-Rank Adaptation (LoRA), parameter-efficient fine-tuning (PEFT), Unsloth quantization, and teacher-student distillation.',
        parentId: 'cat-2',
        parentName: 'Generative AI & Large Language Models',
        courseCount: 4,
        articleCount: 11,
        icon: 'Wrench',
        color: '#f59e0b',
        status: 'Active',
        createdAt: 'Feb 10, 2026',
      },
    ],
  },
  {
    id: 'cat-3',
    name: 'AI Engineering, MLOps & Production Inference',
    slug: 'ai-engineering-mlops',
    description: 'High-throughput model serving engines, quantization, Triton inference servers, continuous evaluation, and GPU cluster management.',
    icon: 'Layers',
    color: '#3b82f6',
    courseCount: 14,
    articleCount: 35,
    status: 'Active',
    createdAt: 'Feb 15, 2026',
    children: [
      {
        id: 'sub-301',
        name: 'vLLM, TensorRT-LLM & Triton Inference Serving',
        slug: 'vllm-triton-serving',
        description: 'Continuous batching, PagedAttention, multi-GPU tensor parallelism, speculative decoding, and model routing.',
        parentId: 'cat-3',
        parentName: 'AI Engineering, MLOps & Production Inference',
        courseCount: 5,
        articleCount: 12,
        icon: 'Zap',
        color: '#3b82f6',
        status: 'Active',
        createdAt: 'Feb 16, 2026',
      },
      {
        id: 'sub-302',
        name: 'Model Quantization (GGUF, AWQ, FP8 & INT4)',
        slug: 'quantization-gguf-awq',
        description: 'Post-training quantization (PTQ), activation-aware weight quantization (AWQ), bitsandbytes 4-bit loading, and GGUF local deployment.',
        parentId: 'cat-3',
        parentName: 'AI Engineering, MLOps & Production Inference',
        courseCount: 4,
        articleCount: 11,
        icon: 'Minimize2',
        color: '#10b981',
        status: 'Active',
        createdAt: 'Feb 18, 2026',
      },
      {
        id: 'sub-303',
        name: 'AI Observability, LLM Evaluations & Guardrails',
        slug: 'ai-observability-guardrails',
        description: 'LangSmith, Arize Phoenix, DeepEval scoring, prompt injection defense, hallucination detection, and red-teaming.',
        parentId: 'cat-3',
        parentName: 'AI Engineering, MLOps & Production Inference',
        courseCount: 5,
        articleCount: 12,
        icon: 'ShieldCheck',
        color: '#ec4899',
        status: 'Active',
        createdAt: 'Feb 20, 2026',
      },
    ],
  },
  {
    id: 'cat-4',
    name: 'Full-Stack Software & Systems Architecture',
    slug: 'software-systems-architecture',
    description: 'Distributed backend systems, database internals, microservices, high-concurrency event brokers, and cloud infrastructure.',
    icon: 'Server',
    color: '#10b981',
    courseCount: 12,
    articleCount: 29,
    status: 'Active',
    createdAt: 'Feb 25, 2026',
    children: [
      {
        id: 'sub-401',
        name: 'Distributed Systems & Microservices (Go / Rust / Node)',
        slug: 'distributed-microservices',
        description: 'gRPC protocols, Raft consensus, Kafka event streaming, circuit breakers, and distributed tracing.',
        parentId: 'cat-4',
        parentName: 'Full-Stack Software & Systems Architecture',
        courseCount: 5,
        articleCount: 10,
        icon: 'FolderTree',
        color: '#10b981',
        status: 'Active',
        createdAt: 'Feb 26, 2026',
      },
      {
        id: 'sub-402',
        name: 'Database Internals, ACID & Query Optimization',
        slug: 'database-internals',
        description: 'B-Tree vs LSM Trees, WAL logs, Postgres indexing, connection pooling, sharding, and transactional concurrency.',
        parentId: 'cat-4',
        parentName: 'Full-Stack Software & Systems Architecture',
        courseCount: 4,
        articleCount: 11,
        icon: 'Database',
        color: '#f59e0b',
        status: 'Active',
        createdAt: 'Feb 27, 2026',
      },
      {
        id: 'sub-403',
        name: 'Cloud Native & Kubernetes GPU Orchestration',
        slug: 'kubernetes-gpu-orchestration',
        description: 'K8s operator patterns, NVIDIA GPU device plugins, Helm charts, autoscaling with KEDA, and cloud cost containment.',
        parentId: 'cat-4',
        parentName: 'Full-Stack Software & Systems Architecture',
        courseCount: 3,
        articleCount: 8,
        icon: 'Cloud',
        color: '#06b6d4',
        status: 'Active',
        createdAt: 'Feb 28, 2026',
      },
    ],
  },
];
