import { ContentType, ContentStatus, AuthorInfo, ContentItem, ContentMetricData, TopCategoryData } from '@/types/content';
export type { ContentType, ContentStatus, AuthorInfo, ContentItem, ContentMetricData, TopCategoryData };


// 1. KPI Metric Cards
export const mockContentMetrics: ContentMetricData[] = [
  {
    id: 'total-content',
    title: 'Total Content',
    value: '1,548',
    change: '20.5%',
    trend: 'up',
    period: 'vs last month',
    variant: 'purple',
  },
  {
    id: 'published',
    title: 'Published',
    value: '842',
    change: '65.7%',
    trend: 'flat',
    period: 'of total',
    variant: 'blue',
  },
  {
    id: 'drafts',
    title: 'Drafts',
    value: '218',
    change: '16.9%',
    trend: 'flat',
    period: 'of total',
    variant: 'orange',
  },
  {
    id: 'pending-review',
    title: 'Pending Review',
    value: '96',
    change: '7.5%',
    trend: 'flat',
    period: 'of total',
    variant: 'green',
  },
  {
    id: 'archived',
    title: 'Archived',
    value: '128',
    change: '10.0%',
    trend: 'flat',
    period: 'of total',
    variant: 'red',
  },
  {
    id: 'views-this-month',
    title: 'Views (This Month)',
    value: '48.6K',
    change: '18.3%',
    trend: 'up',
    period: 'vs last month',
    variant: 'cyan',
  },
];

// 2. Mock Content List matching reference image exactly
export const mockContentList: ContentItem[] = [
  {
    id: 'cnt-1',
    title: 'Introduction to Machine Learning',
    description: 'Fundamentals of ML and its applications',
    type: 'Course',
    category: 'AI & ML',
    subCategory: 'Supervised Learning',
    author: {
      id: 'auth-1',
      name: 'Dr. Alex Morgan',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    },
    status: 'Published',
    views: '12.4K',
    createdAt: 'May 18, 2025',
    thumbnailIcon: 'BookOpen',
  },
  {
    id: 'cnt-2',
    title: 'Neural Networks Explained',
    description: 'Deep dive into ANN and training',
    type: 'Article',
    category: 'Deep Learning',
    subCategory: 'Neural Networks',
    author: {
      id: 'auth-2',
      name: 'Sarah Johnson',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    },
    status: 'Published',
    views: '8.7K',
    createdAt: 'May 17, 2025',
    thumbnailIcon: 'FileText',
  },
  {
    id: 'cnt-3',
    title: 'Python for Data Science',
    description: 'Essential Python libraries guide',
    type: 'Tutorial',
    category: 'Programming',
    subCategory: 'Python',
    author: {
      id: 'auth-3',
      name: 'Michael Smith',
      avatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=150&auto=format&fit=crop&q=80',
    },
    status: 'Draft',
    views: '—',
    createdAt: 'May 16, 2025',
    thumbnailIcon: 'Code',
  },
  {
    id: 'cnt-4',
    title: 'Customer Churn Dataset',
    description: 'Real-world churn prediction dataset',
    type: 'Dataset',
    category: 'Data Science',
    subCategory: 'Datasets',
    author: {
      id: 'auth-4',
      name: 'Emily Davis',
      avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    },
    status: 'Pending Review',
    views: '1.2K',
    createdAt: 'May 15, 2025',
    thumbnailIcon: 'Database',
  },
  {
    id: 'cnt-5',
    title: 'Support Vector Machines',
    description: 'SVM theory and implementation',
    type: 'Article',
    category: 'Machine Learning',
    subCategory: 'Algorithms',
    author: {
      id: 'auth-5',
      name: 'David Wilson',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    },
    status: 'Published',
    views: '6.3K',
    createdAt: 'May 14, 2025',
    thumbnailIcon: 'FileText',
  },
  {
    id: 'cnt-6',
    title: 'Hands-on ML Project',
    description: 'Build a house price prediction model',
    type: 'Video',
    category: 'Projects',
    subCategory: 'End-to-End Projects',
    author: {
      id: 'auth-6',
      name: 'Jessica Lee',
      avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
    },
    status: 'Published',
    views: '9.1K',
    createdAt: 'May 13, 2025',
    thumbnailIcon: 'Video',
  },
  {
    id: 'cnt-7',
    title: 'ML Basics Quiz',
    description: 'Test your machine learning knowledge',
    type: 'Quiz',
    category: 'Assessments',
    subCategory: 'Quizzes',
    author: {
      id: 'auth-7',
      name: 'Daniel Brown',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    },
    status: 'Draft',
    views: '—',
    createdAt: 'May 12, 2025',
    thumbnailIcon: 'HelpCircle',
  },
  {
    id: 'cnt-8',
    title: 'Data Preprocessing Guide',
    description: 'Step-by-step data cleaning techniques',
    type: 'Guide',
    category: 'Data Science',
    subCategory: 'Data Cleaning',
    author: {
      id: 'auth-8',
      name: 'Olivia Martinez',
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    },
    status: 'Published',
    views: '4.8K',
    createdAt: 'May 11, 2025',
    thumbnailIcon: 'Compass',
  },
  {
    id: 'cnt-9',
    title: 'Computer Vision with PyTorch & YOLOv11: Real-Time Pest Detection',
    description: 'Master convolutional neural networks, anchor-free bounding boxes, and real-time inference on edge devices.',
    type: 'Video',
    category: 'AI & ML',
    subCategory: 'Computer Vision',
    author: {
      id: 'auth-1',
      name: 'Dr. Alex Morgan',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    },
    status: 'Published',
    views: '15.4K',
    createdAt: 'May 10, 2025',
    thumbnailIcon: 'Video',
  },
  {
    id: 'cnt-10',
    title: 'Attention Is All You Need: Step-by-Step Transformer Implementation',
    description: 'Vectorized scaled dot-product self-attention, multi-head projections, and positional encoding from ground zero.',
    type: 'Video',
    category: 'Deep Learning',
    subCategory: 'Transformers & LLMs',
    author: {
      id: 'auth-2',
      name: 'Sarah Johnson',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    },
    status: 'Published',
    views: '22.8K',
    createdAt: 'May 09, 2025',
    thumbnailIcon: 'Video',
  },
  {
    id: 'cnt-11',
    title: 'Building Autonomous Multi-Agent Workflows with LangGraph & Ollama',
    description: 'Orchestrate collaborative LLM agents with state graphs, memory retention, tool calling, and local inference.',
    type: 'Video',
    category: 'AI & ML',
    subCategory: 'Agentic Workflows',
    author: {
      id: 'auth-3',
      name: 'Michael Smith',
      avatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=150&auto=format&fit=crop&q=80',
    },
    status: 'Published',
    views: '18.2K',
    createdAt: 'May 08, 2025',
    thumbnailIcon: 'Video',
  },
  {
    id: 'cnt-12',
    title: 'Low-Rank Adaptation (LoRA & QLoRA) for LLaMA 3 Fine-Tuning',
    description: 'Fine-tune 8B and 70B parameter models on consumer GPUs using 4-bit NormalFloat quantization.',
    type: 'Video',
    category: 'Deep Learning',
    subCategory: 'Model Fine-Tuning',
    author: {
      id: 'auth-6',
      name: 'Jessica Lee',
      avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
    },
    status: 'Published',
    views: '14.5K',
    createdAt: 'May 07, 2025',
    thumbnailIcon: 'Video',
  },
  {
    id: 'cnt-13',
    title: 'Precision Agriculture Leaf Disease Classifier: From ResNet to Mobile Deployment',
    description: 'Train custom plant pathology vision models, export to ONNX runtime, and deploy on farmer mobile devices.',
    type: 'Video',
    category: 'Projects',
    subCategory: 'Agriculture AI',
    author: {
      id: 'auth-5',
      name: 'David Wilson',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    },
    status: 'Published',
    views: '11.3K',
    createdAt: 'May 06, 2025',
    thumbnailIcon: 'Video',
  },
  {
    id: 'cnt-14',
    title: 'Diffusion Models Mathematical Intuition: Score-Based SDEs & DDPM',
    description: 'Visual step-by-step masterclass on forward noise addition, reverse denoising U-Nets, and latent sampling.',
    type: 'Video',
    category: 'Deep Learning',
    subCategory: 'Generative Models',
    author: {
      id: 'auth-2',
      name: 'Sarah Johnson',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    },
    status: 'Published',
    views: '8.9K',
    createdAt: 'May 05, 2025',
    thumbnailIcon: 'Video',
  },
  {
    id: 'cnt-15',
    title: 'Production RAG Architecture: Dense Vectors, BM25 Hybrid Search & Cross-Encoder Reranking',
    description: 'Build industrial-grade Retrieval-Augmented Generation with Qdrant, BGE embeddings, Reciprocal Rank Fusion, and RAGAS hallucination metrics.',
    type: 'Article',
    category: 'AI & ML',
    subCategory: 'RAG & Vector Search',
    author: {
      id: 'auth-1',
      name: 'Dr. Alex Morgan',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    },
    status: 'Published',
    views: '26.4K',
    createdAt: 'May 04, 2025',
    thumbnailIcon: 'FileText',
  },
  {
    id: 'cnt-16',
    title: 'Gradient Boosted Decision Trees: XGBoost vs LightGBM vs CatBoost Mathematical Breakdown',
    description: 'Second-order Taylor expansion loss gradients, histogram binning, depth-wise vs leaf-wise growth, and categorical target encoding.',
    type: 'Course',
    category: 'Machine Learning',
    subCategory: 'Tree Ensembles',
    author: {
      id: 'auth-5',
      name: 'David Wilson',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    },
    status: 'Published',
    views: '19.8K',
    createdAt: 'May 03, 2025',
    thumbnailIcon: 'BookOpen',
  },
  {
    id: 'cnt-17',
    title: 'Deep Learning Optimization: AdamW, Learning Rate Warmup & FlashAttention-2 Mechanics',
    description: 'Hardware-aware memory tiling, SRAM vs HBM bandwidth, mixed-precision FP16/BF16 training, and gradient accumulation in PyTorch.',
    type: 'Article',
    category: 'Deep Learning',
    subCategory: 'High Performance DL',
    author: {
      id: 'auth-2',
      name: 'Sarah Johnson',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    },
    status: 'Published',
    views: '21.2K',
    createdAt: 'May 02, 2025',
    thumbnailIcon: 'FileText',
  },
  {
    id: 'cnt-18',
    title: 'Autonomous Multi-Agent Systems: LangGraph State Machines, Reflection Loops & Tool Schemas',
    description: 'Architect multi-agent supervisor hierarchies where planning agents break down software epics into parallel coding and QA worker routines.',
    type: 'Tutorial',
    category: 'AI & ML',
    subCategory: 'Agentic Workflows',
    author: {
      id: 'auth-3',
      name: 'Michael Smith',
      avatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=150&auto=format&fit=crop&q=80',
    },
    status: 'Published',
    views: '31.5K',
    createdAt: 'May 01, 2025',
    thumbnailIcon: 'Code',
  },
  {
    id: 'cnt-19',
    title: 'Enterprise LLM Security: OWASP Top 10 for LLMs, Indirect Prompt Injection & Guardrails',
    description: 'Protect enterprise neural pipelines against jailbreaks, SSRF tool abuse, system prompt leakage, and data poisoning using PyRIT and Guardrails AI.',
    type: 'Guide',
    category: 'AI & ML',
    subCategory: 'AI Cybersecurity',
    author: {
      id: 'auth-1',
      name: 'Dr. Alex Morgan',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    },
    status: 'Published',
    views: '17.9K',
    createdAt: 'Apr 30, 2025',
    thumbnailIcon: 'Shield',
  },
  {
    id: 'cnt-20',
    title: 'Self-Hosted Private AI: Deploying DeepSeek-R1 & Llama 3.3 with vLLM, TensorRT & Ollama',
    description: 'Configure multi-node GPU clusters, KV-cache continuous batching, 4-bit AWQ quantization, and local OpenAI-compatible REST endpoints.',
    type: 'Tutorial',
    category: 'Deep Learning',
    subCategory: 'MLOps & Inference',
    author: {
      id: 'auth-6',
      name: 'Jessica Lee',
      avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
    },
    status: 'Published',
    views: '24.1K',
    createdAt: 'Apr 29, 2025',
    thumbnailIcon: 'Code',
  },

  // ── YOUNG EXPLORER (Class 5–7) ──
  {
    id: 'cnt-21',
    title: 'How Does Google Know What You\'re Searching? AI for Kids Explained',
    description: 'Discover how search engines, voice assistants, and recommendation systems work — explained with fun analogies and simple diagrams for young minds.',
    type: 'Article',
    category: 'AI for Kids',
    subCategory: 'AI Basics',
    author: {
      id: 'auth-9',
      name: 'Ms. Priya Sharma',
      avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    },
    status: 'Published',
    views: '18.6K',
    createdAt: 'Jun 01, 2025',
    thumbnailIcon: 'Sparkles',
  },
  {
    id: 'cnt-22',
    title: 'Train Your Own Image Classifier: Google Teachable Machine Workshop',
    description: 'Step-by-step workshop where kids upload photos, train a classifier, and test it live — no coding required! Learn what "training data" means.',
    type: 'Tutorial',
    category: 'AI for Kids',
    subCategory: 'Hands-on AI',
    author: {
      id: 'auth-9',
      name: 'Ms. Priya Sharma',
      avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    },
    status: 'Published',
    views: '14.2K',
    createdAt: 'Jun 02, 2025',
    thumbnailIcon: 'Code',
  },

  // ── JUNIOR INNOVATOR (Class 8–10) ──
  {
    id: 'cnt-23',
    title: 'Python Basics: Variables, Loops & Your First Data Visualization',
    description: 'Learn Python from scratch — variables, if/else, loops, lists, dictionaries — then create colorful bar charts and pie charts with Matplotlib.',
    type: 'Tutorial',
    category: 'Programming',
    subCategory: 'Python for Beginners',
    author: {
      id: 'auth-3',
      name: 'Michael Smith',
      avatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=150&auto=format&fit=crop&q=80',
    },
    status: 'Published',
    views: '22.1K',
    createdAt: 'Jun 03, 2025',
    thumbnailIcon: 'Code',
  },
  {
    id: 'cnt-24',
    title: 'What is Machine Learning? Predicting Cricket Scores with Data',
    description: 'Understand ML through a cricket prediction project — collect match data, find patterns, and build a simple predictor. Fun, relatable, and visual!',
    type: 'Video',
    category: 'AI & ML',
    subCategory: 'ML for Teens',
    author: {
      id: 'auth-5',
      name: 'David Wilson',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    },
    status: 'Published',
    views: '16.8K',
    createdAt: 'Jun 04, 2025',
    thumbnailIcon: 'Video',
  },

  // ── PRE-UNIVERSITY (Class 11–12 / PUC) ──
  {
    id: 'cnt-25',
    title: 'Probability & Bayes Theorem for AI: Visual Intuition with Real Examples',
    description: 'Master conditional probability, Bayes theorem, prior vs posterior, and understand how spam filters and medical diagnosis AI actually work.',
    type: 'Article',
    category: 'Mathematics',
    subCategory: 'Probability & Statistics',
    author: {
      id: 'auth-1',
      name: 'Dr. Alex Morgan',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    },
    status: 'Published',
    views: '11.3K',
    createdAt: 'Jun 05, 2025',
    thumbnailIcon: 'FileText',
  },
  {
    id: 'cnt-26',
    title: 'Linear Regression from Scratch: Gradient Descent Step-by-Step',
    description: 'Implement linear regression using only NumPy — understand cost functions, gradient computation, learning rate, and convergence with animations.',
    type: 'Tutorial',
    category: 'Machine Learning',
    subCategory: 'From Scratch',
    author: {
      id: 'auth-2',
      name: 'Sarah Johnson',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    },
    status: 'Published',
    views: '13.7K',
    createdAt: 'Jun 06, 2025',
    thumbnailIcon: 'Code',
  },

  // ── UNDERGRADUATE (B.Tech / BSc) ──
  {
    id: 'cnt-27',
    title: 'Convolutional Neural Networks Explained: Kernels, Feature Maps & Pooling',
    description: 'Visual deep-dive into CNN architecture — convolution operations, activation maps, max pooling, flattening, and building LeNet-5 from scratch in PyTorch.',
    type: 'Video',
    category: 'Deep Learning',
    subCategory: 'Computer Vision',
    author: {
      id: 'auth-2',
      name: 'Sarah Johnson',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    },
    status: 'Published',
    views: '19.4K',
    createdAt: 'Jun 07, 2025',
    thumbnailIcon: 'Video',
  },
  {
    id: 'cnt-28',
    title: 'Natural Language Processing with Transformers: Tokenization to Fine-Tuning',
    description: 'Complete NLP pipeline — BPE/WordPiece tokenization, embeddings, BERT fine-tuning for sentiment analysis, and HuggingFace Transformers library.',
    type: 'Course',
    category: 'AI & ML',
    subCategory: 'NLP',
    author: {
      id: 'auth-1',
      name: 'Dr. Alex Morgan',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    },
    status: 'Published',
    views: '25.6K',
    createdAt: 'Jun 08, 2025',
    thumbnailIcon: 'BookOpen',
  },

  // ── POSTGRADUATE (M.Tech / MSc) ──
  {
    id: 'cnt-29',
    title: 'Graph Neural Networks: Message Passing, GCN & Real-World Applications',
    description: 'Spectral vs spatial graph convolutions, GCN/GAT architectures, molecular property prediction, social network analysis, and PyTorch Geometric.',
    type: 'Article',
    category: 'Deep Learning',
    subCategory: 'Graph ML',
    author: {
      id: 'auth-2',
      name: 'Sarah Johnson',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    },
    status: 'Published',
    views: '8.4K',
    createdAt: 'Jun 09, 2025',
    thumbnailIcon: 'FileText',
  },
  {
    id: 'cnt-30',
    title: 'Federated Learning & Privacy-Preserving AI for Enterprise',
    description: 'Train models across distributed devices without sharing raw data — differential privacy, secure aggregation, FedAvg, and healthcare/finance use cases.',
    type: 'Guide',
    category: 'AI & ML',
    subCategory: 'Privacy & Security',
    author: {
      id: 'auth-1',
      name: 'Dr. Alex Morgan',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    },
    status: 'Published',
    views: '6.9K',
    createdAt: 'Jun 10, 2025',
    thumbnailIcon: 'Shield',
  },

  // ── PHD & RESEARCH ──
  {
    id: 'cnt-31',
    title: 'Mechanistic Interpretability: Probing Transformer Circuits & Features',
    description: 'Understand transformer internals through circuit analysis — attention head specialization, superposition, sparse autoencoders, and Anthropic\'s feature visualization.',
    type: 'Article',
    category: 'Research',
    subCategory: 'Interpretability',
    author: {
      id: 'auth-2',
      name: 'Sarah Johnson',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    },
    status: 'Published',
    views: '4.2K',
    createdAt: 'Jun 11, 2025',
    thumbnailIcon: 'FileText',
  },
  {
    id: 'cnt-32',
    title: 'Diffusion Models Theory: Score Matching, Langevin Dynamics & Classifier-Free Guidance',
    description: 'Mathematical foundations of diffusion models — forward/reverse SDE, score estimation, noise scheduling, DDPM vs DDIM, and CFG for controllable generation.',
    type: 'Article',
    category: 'Research',
    subCategory: 'Generative Models',
    author: {
      id: 'auth-1',
      name: 'Dr. Alex Morgan',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    },
    status: 'Published',
    views: '5.1K',
    createdAt: 'Jun 12, 2025',
    thumbnailIcon: 'FileText',
  },
];

// 3. Top Categories Data with Max Reference
export const mockTopCategories: TopCategoryData[] = [
  { id: 'cat-1', name: 'AI & ML', count: 324, maxCount: 380 },
  { id: 'cat-2', name: 'Data Science', count: 256, maxCount: 380 },
  { id: 'cat-3', name: 'Deep Learning', count: 218, maxCount: 380 },
  { id: 'cat-4', name: 'Programming', count: 194, maxCount: 380 },
  { id: 'cat-5', name: 'AI for Kids', count: 164, maxCount: 380 },
  { id: 'cat-6', name: 'Mathematics', count: 148, maxCount: 380 },
  { id: 'cat-7', name: 'Research & Papers', count: 112, maxCount: 380 },
  { id: 'cat-8', name: 'Projects', count: 142, maxCount: 380 },
];

// 4. Recent Content Activities
export const mockRecentContentActivities = [
  {
    id: 'c-act-1',
    title: 'New content "Data Preprocessing Guide" created',
    author: 'Olivia Martinez',
    time: '30 min ago',
    iconName: 'PlusCircle',
    iconColor: 'text-purple-400 bg-purple-500/10',
  },
  {
    id: 'c-act-2',
    title: 'Content "ML Basics Quiz" moved to Draft',
    author: 'Daniel Brown',
    time: '1 hour ago',
    iconName: 'FileEdit',
    iconColor: 'text-amber-400 bg-amber-500/10',
  },
  {
    id: 'c-act-3',
    title: 'Content "Customer Churn Dataset" submitted for review',
    author: 'Emily Davis',
    time: '2 hours ago',
    iconName: 'Clock',
    iconColor: 'text-emerald-400 bg-emerald-500/10',
  },
  {
    id: 'c-act-4',
    title: 'Content "Neural Networks Explained" published',
    author: 'Sarah Johnson',
    time: '3 hours ago',
    iconName: 'CheckCircle2',
    iconColor: 'text-blue-400 bg-blue-500/10',
  },
];
