import { PermissionState, PermissionType, RoleColumnHeader, PermissionRowItem, PermissionModuleGroup, PermissionMetricData, SinglePermission } from '@/types/permission';
export type { PermissionState, PermissionType, RoleColumnHeader, PermissionRowItem, PermissionModuleGroup, PermissionMetricData, SinglePermission };


// 1. KPI Metric Cards
export const mockPermissionMetrics: PermissionMetricData[] = [
  {
    id: 'total-permissions',
    title: 'Total Permissions',
    value: '186',
    change: '6 new',
    trend: 'up',
    period: 'this month',
    variant: 'purple',
  },
  {
    id: 'modules',
    title: 'Modules',
    value: '24',
    change: 'Across',
    trend: 'flat',
    period: 'the system',
    variant: 'blue',
  },
  {
    id: 'assigned-permissions',
    title: 'Assigned Permissions',
    value: '182',
    change: '97.8%',
    trend: 'flat',
    period: 'of total',
    variant: 'green',
  },
  {
    id: 'custom-permissions',
    title: 'Custom Permissions',
    value: '12',
    change: 'Created',
    trend: 'flat',
    period: 'by admins',
    variant: 'orange',
  },
  {
    id: 'roles-using-permissions',
    title: 'Roles Using Permissions',
    value: '10',
    change: 'Using',
    trend: 'flat',
    period: 'these permissions',
    variant: 'purple',
  },
];

// 2. Role Columns
export const mockRoleColumns: RoleColumnHeader[] = [
  { id: 'super-admin', name: 'Super Admin', type: 'System' },
  { id: 'admin', name: 'Admin', type: 'System' },
  { id: 'manager', name: 'Manager', type: 'Custom' },
  { id: 'instructor', name: 'Instructor', type: 'Custom' },
  { id: 'viewer', name: 'Viewer', type: 'Custom' },
  { id: 'support', name: 'Support', type: 'Custom' },
  { id: 'guest', name: 'Guest', type: 'System' },
];

// 3. Permission Matrix Modules matching reference screenshot
export const mockPermissionModulesData: PermissionModuleGroup[] = [
  {
    id: 'mod-user-mgmt',
    name: 'User Management',
    iconName: 'Users',
    resourceCount: 4,
    isExpanded: true,
    roleAggregates: {
      'super-admin': { granted: 18, denied: 0, notSet: 0 },
      admin: { granted: 16, denied: 0, notSet: 2 },
      manager: { granted: 12, denied: 4, notSet: 2 },
      instructor: { granted: 6, denied: 10, notSet: 2 },
      viewer: { granted: 2, denied: 14, notSet: 2 },
      support: { granted: 10, denied: 6, notSet: 2 },
      guest: { granted: 0, denied: 18, notSet: 0 },
    },
    rows: [
      {
        id: 'p-1',
        resource: 'Users',
        resourceDesc: 'Manage platform users',
        action: 'View',
        actionDesc: 'Create permissions',
        roleStates: {
          'super-admin': 'granted',
          admin: 'granted',
          manager: 'granted',
          instructor: 'not-set',
          viewer: 'denied',
          support: 'granted',
          guest: 'denied',
        },
      },
      {
        id: 'p-2',
        resource: 'Users',
        resourceDesc: 'Manage platform users',
        action: 'View',
        actionDesc: 'Edits',
        roleStates: {
          'super-admin': 'granted',
          admin: 'granted',
          manager: 'granted',
          instructor: 'denied',
          viewer: 'denied',
          support: 'not-set',
          guest: 'denied',
        },
      },
      {
        id: 'p-3',
        resource: 'Roles',
        resourceDesc: 'Manage roles',
        action: 'View',
        actionDesc: 'Scope all permissions',
        roleStates: {
          'super-admin': 'granted',
          admin: 'granted',
          manager: 'denied',
          instructor: 'denied',
          viewer: 'denied',
          support: 'denied',
          guest: 'denied',
        },
      },
      {
        id: 'p-4',
        resource: 'Permissions',
        resourceDesc: 'Manage all permissions',
        action: 'View',
        actionDesc: 'Manage user sessions',
        roleStates: {
          'super-admin': 'granted',
          admin: 'granted',
          manager: 'granted',
          instructor: 'not-set',
          viewer: 'denied',
          support: 'denied',
          guest: 'denied',
        },
      },
      {
        id: 'p-5',
        resource: 'Sessions',
        resourceDesc: 'Manage user sessions',
        action: 'View',
        actionDesc: 'Viewer activity logs',
        roleStates: {
          'super-admin': 'granted',
          admin: 'granted',
          manager: 'granted',
          instructor: 'not-set',
          viewer: 'denied',
          support: 'granted',
          guest: 'denied',
        },
      },
    ],
  },
  {
    id: 'mod-content-mgmt',
    name: 'Content Management',
    iconName: 'FileText',
    resourceCount: 5,
    isExpanded: false,
    roleAggregates: {
      'super-admin': { granted: 32, denied: 0, notSet: 0 },
      admin: { granted: 24, denied: 8, notSet: 0 },
      manager: { granted: 18, denied: 14, notSet: 0 },
      instructor: { granted: 10, denied: 22, notSet: 0 },
      viewer: { granted: 6, denied: 26, notSet: 0 },
      support: { granted: 12, denied: 20, notSet: 0 },
      guest: { granted: 6, denied: 26, notSet: 0 },
    },
    rows: [
      {
        id: 'p-6',
        resource: 'Articles',
        resourceDesc: 'Manage articles',
        action: 'View / Edit',
        actionDesc: 'Article publishing',
        roleStates: {
          'super-admin': 'granted',
          admin: 'granted',
          manager: 'granted',
          instructor: 'granted',
          viewer: 'granted',
          support: 'not-set',
          guest: 'denied',
        },
      },
    ],
  },
  {
    id: 'mod-courses',
    name: 'Courses',
    iconName: 'GraduationCap',
    resourceCount: 6,
    isExpanded: false,
    roleAggregates: {
      'super-admin': { granted: 36, denied: 0, notSet: 0 },
      admin: { granted: 28, denied: 8, notSet: 0 },
      manager: { granted: 20, denied: 16, notSet: 0 },
      instructor: { granted: 12, denied: 24, notSet: 0 },
      viewer: { granted: 6, denied: 30, notSet: 0 },
      support: { granted: 14, denied: 22, notSet: 0 },
      guest: { granted: 6, denied: 30, notSet: 0 },
    },
    rows: [
      {
        id: 'p-7',
        resource: 'Course Curriculum',
        resourceDesc: 'Manage course modules',
        action: 'Edit',
        actionDesc: 'Curriculum creation',
        roleStates: {
          'super-admin': 'granted',
          admin: 'granted',
          manager: 'granted',
          instructor: 'granted',
          viewer: 'denied',
          support: 'not-set',
          guest: 'denied',
        },
      },
    ],
  },
  {
    id: 'mod-projects',
    name: 'Projects',
    iconName: 'FolderGit2',
    resourceCount: 4,
    isExpanded: false,
    roleAggregates: {
      'super-admin': { granted: 28, denied: 0, notSet: 0 },
      admin: { granted: 20, denied: 8, notSet: 0 },
      manager: { granted: 14, denied: 14, notSet: 0 },
      instructor: { granted: 8, denied: 20, notSet: 0 },
      viewer: { granted: 4, denied: 24, notSet: 0 },
      support: { granted: 10, denied: 18, notSet: 0 },
      guest: { granted: 4, denied: 24, notSet: 0 },
    },
    rows: [
      {
        id: 'p-8',
        resource: 'AI Repositories',
        resourceDesc: 'Manage codebase repos',
        action: 'Manage',
        actionDesc: 'Repository commit access',
        roleStates: {
          'super-admin': 'granted',
          admin: 'granted',
          manager: 'granted',
          instructor: 'not-set',
          viewer: 'denied',
          support: 'denied',
          guest: 'denied',
        },
      },
    ],
  },
  {
    id: 'mod-assessments',
    name: 'Assessments',
    iconName: 'ClipboardCheck',
    resourceCount: 5,
    isExpanded: false,
    roleAggregates: {
      'super-admin': { granted: 30, denied: 0, notSet: 0 },
      admin: { granted: 22, denied: 8, notSet: 0 },
      manager: { granted: 16, denied: 14, notSet: 0 },
      instructor: { granted: 10, denied: 20, notSet: 0 },
      viewer: { granted: 6, denied: 24, notSet: 0 },
      support: { granted: 12, denied: 18, notSet: 0 },
      guest: { granted: 6, denied: 24, notSet: 0 },
    },
    rows: [
      {
        id: 'p-9',
        resource: 'Quizzes & Grading',
        resourceDesc: 'Manage assessment rubrics',
        action: 'Grade',
        actionDesc: 'Student evaluation',
        roleStates: {
          'super-admin': 'granted',
          admin: 'granted',
          manager: 'granted',
          instructor: 'granted',
          viewer: 'denied',
          support: 'not-set',
          guest: 'denied',
        },
      },
    ],
  },
];

// 4. Popular Permissions List
export const mockPopularPermissions = [
  { id: 'pop-1', title: 'View Users', rolesCount: '10 Roles', iconName: 'Eye' },
  { id: 'pop-2', title: 'Edit Content', rolesCount: '9 Roles', iconName: 'Edit3' },
  { id: 'pop-3', title: 'Manage Courses', rolesCount: '8 Roles', iconName: 'GraduationCap' },
  { id: 'pop-4', title: 'View Reports', rolesCount: '8 Roles', iconName: 'BarChart2' },
  { id: 'pop-5', title: 'Manage Projects', rolesCount: '7 Roles', iconName: 'FolderGit2' },
];

// 5. Recent Permission Audit Log Activities
export const mockRecentPermissionActivities = [
  {
    id: 'p-act-1',
    title: 'Custom permission "Export Reports" created',
    author: 'Super Admin',
    time: '2 hours ago',
    iconName: 'PlusCircle',
    iconColor: 'text-emerald-400 bg-emerald-500/10',
  },
  {
    id: 'p-act-2',
    title: 'Permission "Delete Users" updated',
    author: 'Admin',
    time: '5 hours ago',
    iconName: 'Edit',
    iconColor: 'text-blue-400 bg-blue-500/10',
  },
  {
    id: 'p-act-3',
    title: 'Permission assigned to role "Instructor"',
    author: 'Manager',
    time: '1 day ago',
    iconName: 'ShieldCheck',
    iconColor: 'text-purple-400 bg-purple-500/10',
  },
];

// 6. Flat Permissions List dataset for Permissions List Tab
export const mockFlatPermissionsList: SinglePermission[] = [
  {
    id: 'perm-1',
    key: 'users.view',
    name: 'View Users',
    module: 'User Management',
    resource: 'Users',
    action: 'View',
    type: 'System',
    rolesUsing: 10,
    status: 'Active',
    createdAt: 'Jan 10, 2024',
  },
  {
    id: 'perm-2',
    key: 'users.create',
    name: 'Create Users',
    module: 'User Management',
    resource: 'Users',
    action: 'Create',
    type: 'System',
    rolesUsing: 4,
    status: 'Active',
    createdAt: 'Jan 10, 2024',
  },
  {
    id: 'perm-3',
    key: 'users.edit',
    name: 'Edit Users',
    module: 'User Management',
    resource: 'Users',
    action: 'Edit',
    type: 'System',
    rolesUsing: 3,
    status: 'Active',
    createdAt: 'Jan 12, 2024',
  },
  {
    id: 'perm-4',
    key: 'reports.export',
    name: 'Export Reports',
    module: 'Analytics',
    resource: 'Reports',
    action: 'Export',
    type: 'Custom',
    rolesUsing: 3,
    status: 'Active',
    createdAt: 'May 10, 2025',
  },
  {
    id: 'perm-5',
    key: 'ai.prompt.edit',
    name: 'Edit Prompts',
    module: 'AI Control Center',
    resource: 'Prompts',
    action: 'Edit',
    type: 'Custom',
    rolesUsing: 2,
    status: 'Active',
    createdAt: 'May 12, 2025',
  },
];
