import { RoleType, RoleStatus, RoleItem, RoleMetricData, PermissionModule } from '@/types/role';
export type { RoleType, RoleStatus, RoleItem, RoleMetricData, PermissionModule };


// 1. Roles Metric Cards
export const mockRoleMetrics: RoleMetricData[] = [
  {
    id: 'total-roles',
    title: 'Total Roles',
    value: '12',
    change: '2 new',
    trend: 'up',
    period: 'this month',
    variant: 'purple',
  },
  {
    id: 'active-roles',
    title: 'Active Roles',
    value: '9',
    change: '75%',
    trend: 'flat',
    period: 'of total roles',
    variant: 'blue',
  },
  {
    id: 'custom-roles',
    title: 'Custom Roles',
    value: '8',
    change: '66%',
    trend: 'flat',
    period: 'are custom roles',
    variant: 'orange',
  },
  {
    id: 'users-with-roles',
    title: 'Users with Roles',
    value: '12,458',
    change: 'Across',
    trend: 'flat',
    period: 'all roles',
    variant: 'green',
  },
  {
    id: 'total-permissions',
    title: 'Permissions',
    value: '186',
    change: 'Across',
    trend: 'flat',
    period: 'all roles',
    variant: 'purple',
  },
  {
    id: 'system-roles',
    title: 'System Roles',
    value: '4',
    change: 'Cannot',
    trend: 'flat',
    period: 'be deleted',
    variant: 'red',
  },
];

// 2. Mock Roles List (matching reference screenshot)
export const mockRolesList: RoleItem[] = [
  {
    id: 'role-1',
    name: 'Super Admin',
    type: 'System',
    usersCount: 3,
    userPercentage: 0.02,
    permissionsCount: 186,
    description: 'Full system access with all permissions',
    status: 'Active',
    iconName: 'ShieldAlert',
    iconBg: 'bg-purple-600/20',
    iconColor: 'text-purple-400',
    isProtected: true,
    createdAt: 'Jan 10, 2024',
    updatedAt: 'May 18, 2025',
  },
  {
    id: 'role-2',
    name: 'Admin',
    type: 'System',
    usersCount: 18,
    userPercentage: 0.14,
    permissionsCount: 142,
    description: 'Manage platform settings and users',
    status: 'Active',
    iconName: 'Shield',
    iconBg: 'bg-blue-600/20',
    iconColor: 'text-blue-400',
    isProtected: true,
    createdAt: 'Jan 12, 2024',
    updatedAt: 'May 17, 2025',
  },
  {
    id: 'role-3',
    name: 'Manager',
    type: 'Custom',
    usersCount: 105,
    userPercentage: 0.84,
    permissionsCount: 98,
    description: 'Manage content, users and reports',
    status: 'Active',
    iconName: 'Users',
    iconBg: 'bg-blue-500/20',
    iconColor: 'text-blue-400',
    isProtected: false,
    createdAt: 'Feb 01, 2024',
    updatedAt: 'May 16, 2025',
  },
  {
    id: 'role-4',
    name: 'Content Manager',
    type: 'Custom',
    usersCount: 236,
    userPercentage: 1.89,
    permissionsCount: 76,
    description: 'Create and manage content',
    status: 'Active',
    iconName: 'FileText',
    iconBg: 'bg-emerald-600/20',
    iconColor: 'text-emerald-400',
    isProtected: false,
    createdAt: 'Feb 15, 2024',
    updatedAt: 'May 15, 2025',
  },
  {
    id: 'role-5',
    name: 'Instructor',
    type: 'Custom',
    usersCount: 842,
    userPercentage: 6.76,
    permissionsCount: 64,
    description: 'Manage courses and student progress',
    status: 'Active',
    iconName: 'GraduationCap',
    iconBg: 'bg-amber-600/20',
    iconColor: 'text-amber-400',
    isProtected: false,
    createdAt: 'Mar 01, 2024',
    updatedAt: 'May 14, 2025',
  },
  {
    id: 'role-6',
    name: 'Analyst',
    type: 'Custom',
    usersCount: 156,
    userPercentage: 1.25,
    permissionsCount: 52,
    description: 'View analytics and generate reports',
    status: 'Active',
    iconName: 'BarChart2',
    iconBg: 'bg-amber-500/20',
    iconColor: 'text-amber-400',
    isProtected: false,
    createdAt: 'Mar 10, 2024',
    updatedAt: 'May 12, 2025',
  },
  {
    id: 'role-7',
    name: 'Support',
    type: 'Custom',
    usersCount: 98,
    userPercentage: 0.79,
    permissionsCount: 38,
    description: 'Handle user support and tickets',
    status: 'Active',
    iconName: 'Headphones',
    iconBg: 'bg-cyan-600/20',
    iconColor: 'text-cyan-400',
    isProtected: false,
    createdAt: 'Mar 20, 2024',
    updatedAt: 'May 10, 2025',
  },
  {
    id: 'role-8',
    name: 'Viewer',
    type: 'Custom',
    usersCount: 5421,
    userPercentage: 43.50,
    permissionsCount: 12,
    description: 'Read-only access to assigned modules',
    status: 'Active',
    iconName: 'Eye',
    iconBg: 'bg-rose-600/20',
    iconColor: 'text-rose-400',
    isProtected: false,
    createdAt: 'Apr 01, 2024',
    updatedAt: 'May 08, 2025',
  },
  {
    id: 'role-9',
    name: 'Guest',
    type: 'System',
    usersCount: 2037,
    userPercentage: 16.34,
    permissionsCount: 6,
    description: 'Limited access for guests',
    status: 'Inactive',
    iconName: 'Lock',
    iconBg: 'bg-[#23232f]',
    iconColor: 'text-zinc-400',
    isProtected: true,
    createdAt: 'Jan 01, 2024',
    updatedAt: 'May 01, 2025',
  },
  {
    id: 'role-10',
    name: 'Banned',
    type: 'System',
    usersCount: 0,
    userPercentage: 0,
    permissionsCount: 0,
    description: 'No access - blocked role',
    status: 'Inactive',
    iconName: 'UserX',
    iconBg: 'bg-[#23232f]',
    iconColor: 'text-zinc-500',
    isProtected: true,
    createdAt: 'Jan 01, 2024',
    updatedAt: 'Apr 15, 2025',
  },
];

// 3. Permission Overview Stats
export const mockPermissionOverview = {
  totalPermissions: 186,
  assignedPermissions: 182,
  unassignedPermissions: 4,
  modulesWithAccess: 24,
  resourcesWithAccess: 156,
};

// 4. Recent Role Activities
export const mockRecentRoleActivities = [
  {
    id: 'act-1',
    title: 'New role "Data Scientist" created',
    author: 'Super Admin',
    time: '2 hours ago',
    iconName: 'ShieldAlert',
    iconColor: 'text-purple-400 bg-purple-500/10',
  },
  {
    id: 'act-2',
    title: 'Permissions updated for "Manager"',
    author: 'Admin',
    time: '5 hours ago',
    iconName: 'Shield',
    iconColor: 'text-blue-400 bg-blue-500/10',
  },
  {
    id: 'act-3',
    title: 'Role "Editor" deleted',
    author: 'Super Admin',
    time: '1 day ago',
    iconName: 'FileText',
    iconColor: 'text-emerald-400 bg-emerald-500/10',
  },
];

// 5. Default Modular Permissions Matrix for Modal
export const mockPermissionModules: PermissionModule[] = [
  {
    id: 'user-mgmt',
    name: 'User Management',
    description: 'Manage platform user accounts and profiles',
    permissions: [
      { id: 'user_view', label: 'View Users', granted: true },
      { id: 'user_create', label: 'Create Users', granted: true },
      { id: 'user_edit', label: 'Edit Users', granted: true },
      { id: 'user_delete', label: 'Delete Users', granted: false },
    ],
  },
  {
    id: 'role-mgmt',
    name: 'Role & Security',
    description: 'Manage access control and RBAC policies',
    permissions: [
      { id: 'role_view', label: 'View Roles', granted: true },
      { id: 'role_create', label: 'Create Roles', granted: true },
      { id: 'role_edit', label: 'Edit Permissions', granted: true },
      { id: 'role_delete', label: 'Delete Roles', granted: false },
    ],
  },
  {
    id: 'ai-control',
    name: 'AI Control Center',
    description: 'Model deployment, prompt engineering & usage limits',
    permissions: [
      { id: 'ai_view', label: 'View Models', granted: true },
      { id: 'ai_config', label: 'Configure Models', granted: true },
      { id: 'ai_prompt', label: 'Manage Prompts', granted: true },
      { id: 'ai_cost', label: 'View Cost & Tokens', granted: true },
    ],
  },
];
