import { UserRole, UserStatus, UserItem, UserMetricData } from '@/types/user';
export type { UserRole, UserStatus, UserItem, UserMetricData };


// User Metrics matching reference image
export const mockUserMetrics: UserMetricData[] = [
  {
    id: 'total-users',
    title: 'Total Users',
    value: '12,458',
    change: '12.5%',
    trend: 'up',
    period: 'vs last 7 days',
    variant: 'purple',
  },
  {
    id: 'active-users',
    title: 'Active Users',
    value: '11,245',
    change: '8.4%',
    trend: 'up',
    period: 'vs last 7 days',
    variant: 'blue',
  },
  {
    id: 'inactive-users',
    title: 'Inactive Users',
    value: '832',
    change: '3.2%',
    trend: 'down',
    period: 'vs last 7 days',
    variant: 'green',
  },
  {
    id: 'pending-users',
    title: 'Pending Users',
    value: '147',
    change: '5.6%',
    trend: 'up',
    period: 'vs last 7 days',
    variant: 'orange',
  },
  {
    id: 'suspended-users',
    title: 'Suspended Users',
    value: '234',
    change: '2.1%',
    trend: 'down',
    period: 'vs last 7 days',
    variant: 'red',
  },
  {
    id: 'deleted-users',
    title: 'Deleted Users',
    value: '1,821',
    change: 'No change',
    trend: 'flat',
    period: 'vs last 7 days',
    variant: 'purple',
  },
];

// Mock Users Dataset matching reference table rows exactly
export const mockUsersList: UserItem[] = [
  {
    id: 'usr-1',
    name: 'John Doe',
    username: '@johndoe',
    email: 'john.doe@example.com',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
    role: 'Admin',
    organization: 'AI Research Lab',
    status: 'Active',
    emailVerified: true,
    lastActive: '2 min ago',
    createdAt: 'May 18, 2025',
  },
  {
    id: 'usr-2',
    name: 'Emma Johnson',
    username: '@emmaj',
    email: 'emma.johnson@example.com',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    role: 'Manager',
    organization: 'Data Science Team',
    status: 'Active',
    emailVerified: true,
    lastActive: '15 min ago',
    createdAt: 'May 17, 2025',
  },
  {
    id: 'usr-3',
    name: 'Michael Smith',
    username: '@michaels',
    email: 'michael.smith@example.com',
    avatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=150&auto=format&fit=crop&q=80',
    role: 'Editor',
    organization: 'Content Team',
    status: 'Inactive',
    emailVerified: true,
    lastActive: '2 days ago',
    createdAt: 'May 15, 2025',
  },
  {
    id: 'usr-4',
    name: 'Sophia Lee',
    username: '@sophialee',
    email: 'sophia.lee@example.com',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    role: 'Instructor',
    organization: 'AI Learning Program',
    status: 'Active',
    emailVerified: false,
    lastActive: '1 hour ago',
    createdAt: 'May 14, 2025',
  },
  {
    id: 'usr-5',
    name: 'David Brown',
    username: '@davidbrown',
    email: 'david.brown@example.com',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    role: 'User',
    organization: 'General',
    status: 'Pending',
    emailVerified: false,
    lastActive: '—',
    createdAt: 'May 18, 2025',
  },
  {
    id: 'usr-6',
    name: 'Olivia Wilson',
    username: '@oliviaw',
    email: 'olivia.wilson@example.com',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    role: 'User',
    organization: 'General',
    status: 'Suspended',
    emailVerified: true,
    lastActive: '3 days ago',
    createdAt: 'May 13, 2025',
  },
  {
    id: 'usr-7',
    name: 'Liam Anderson',
    username: '@liamanderson',
    email: 'liam.anderson@example.com',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    role: 'Analyst',
    organization: 'Analytics Team',
    status: 'Active',
    emailVerified: true,
    lastActive: '5 min ago',
    createdAt: 'May 12, 2025',
  },
  {
    id: 'usr-8',
    name: 'Ava Martinez',
    username: '@avamartinez',
    email: 'ava.martinez@example.com',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    role: 'Moderator',
    organization: 'Community Team',
    status: 'Active',
    emailVerified: true,
    lastActive: '10 min ago',
    createdAt: 'May 11, 2025',
  },
  {
    id: 'usr-9',
    name: 'Noah Taylor',
    username: '@noahtaylor',
    email: 'noah.taylor@example.com',
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    role: 'Manager',
    organization: 'AI Research Lab',
    status: 'Active',
    emailVerified: true,
    lastActive: '18 min ago',
    createdAt: 'May 10, 2025',
  },
  {
    id: 'usr-10',
    name: 'Isabella White',
    username: '@isabellaw',
    email: 'isabella.white@example.com',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    role: 'Editor',
    organization: 'Content Team',
    status: 'Active',
    emailVerified: true,
    lastActive: '1 day ago',
    createdAt: 'May 09, 2025',
  },
  {
    id: 'usr-11',
    name: 'Ethan Harris',
    username: '@ethanh',
    email: 'ethan.harris@example.com',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    role: 'User',
    organization: 'General',
    status: 'Deleted',
    emailVerified: false,
    lastActive: '—',
    createdAt: 'May 08, 2025',
  },
  {
    id: 'usr-12',
    name: 'Mia Clark',
    username: '@miaclark',
    email: 'mia.clark@example.com',
    avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80',
    role: 'Instructor',
    organization: 'AI Learning Program',
    status: 'Active',
    emailVerified: true,
    lastActive: '45 min ago',
    createdAt: 'May 07, 2025',
  },
];
