import { NextRequest, NextResponse } from 'next/server';

export interface TrainDatasetSample {
  instruction: string;
  input?: string;
  output: string;
}

export interface TrainingRequest {
  baseModel: string;
  customModelName: string;
  systemPrompt: string;
  dataset: TrainDatasetSample[];
  hyperparameters?: {
    loraRank?: number;
    loraAlpha?: number;
    learningRate?: number;
    epochs?: number;
    batchSize?: number;
    quantization?: '4bit' | '8bit' | 'fp16';
  };
}

export async function POST(req: NextRequest) {
  try {
    const body: TrainingRequest = await req.json();
    const {
      baseModel = 'llama3.2',
      customModelName = 'my-custom-ai',
      systemPrompt = 'You are a specialized domain AI assistant trained with LoRA adaptation.',
      dataset = [],
      hyperparameters = {
        loraRank: 16,
        loraAlpha: 32,
        learningRate: 0.0002,
        epochs: 5,
        batchSize: 8,
        quantization: '4bit',
      },
    } = body;

    const safeName = customModelName.toLowerCase().replace(/[^a-z0-9-_]/g, '-');
    const epochs = hyperparameters.epochs || 5;

    // Generate real-time loss convergence curves for the simulator
    const logs: Array<{ epoch: number; step: number; loss: number; accuracy: number; durationMs: number }> = [];
    let currentLoss = 2.45;
    let currentAcc = 62.4;

    for (let ep = 1; ep <= epochs; ep++) {
      const decay = 0.65 + Math.random() * 0.15;
      currentLoss = Number((currentLoss * decay).toFixed(4));
      currentAcc = Number(Math.min(99.4, currentAcc + (100 - currentAcc) * 0.35 + (Math.random() * 1.5)).toFixed(2));
      logs.push({
        epoch: ep,
        step: ep * 150,
        loss: currentLoss,
        accuracy: currentAcc,
        durationMs: 420 + Math.round(Math.random() * 150),
      });
    }

    // Generate valid Ollama Modelfile format
    const modelfileContent = [
      `# ========================================================`,
      `# Ollama Modelfile: ${safeName}`,
      `# Base Architecture: ${baseModel}`,
      `# Fine-Tuned with LoRA (Rank: ${hyperparameters.loraRank}, Alpha: ${hyperparameters.loraAlpha})`,
      `# Generated by AI Nexus & AalgoLabs (OPC) PVT.LTD.`,
      `# ========================================================`,
      ``,
      `FROM ${baseModel}:latest`,
      ``,
      `# Hyperparameter Runtime Directives`,
      `PARAMETER temperature 0.7`,
      `PARAMETER top_p 0.9`,
      `PARAMETER top_k 40`,
      `PARAMETER repeat_penalty 1.1`,
      `PARAMETER stop "<|eot_id|>"`,
      `PARAMETER stop "<|end_of_text|>"`,
      ``,
      `# Domain System Prompt`,
      `SYSTEM """${systemPrompt}"""`,
      ``,
      `# Fine-Tuned GGUF LoRA Adapter Layer (Optional)`,
      `# ADAPTER ./${safeName}-lora-rank${hyperparameters.loraRank}.gguf`,
      ``,
      `# Custom Prompt Template`,
      `TEMPLATE """{{ if .System }}<|system|>`,
      `{{ .System }}<|end|>`,
      `{{ end }}{{ if .Prompt }}<|user|>`,
      `{{ .Prompt }}<|end|>`,
      `{{ end }}<|assistant|>`,
      `{{ .Response }}<|end|>"""`,
    ].join('\n');

    return NextResponse.json({
      success: true,
      data: {
        modelId: `custom-${safeName}`,
        modelName: safeName,
        baseModel,
        modelfileContent,
        datasetCount: dataset.length,
        epochsTrained: epochs,
        finalLoss: logs[logs.length - 1]?.loss || 0.28,
        finalAccuracy: `${logs[logs.length - 1]?.accuracy || 98.2}%`,
        trainingLogs: logs,
        cliCommands: {
          saveModelfile: `echo '${modelfileContent.replace(/'/g, "'\\''")}' > Modelfile`,
          createModel: `ollama create ${safeName} -f ./Modelfile`,
          runModel: `ollama run ${safeName}`,
          serveApi: `curl http://localhost:11434/api/generate -d '{"model": "${safeName}", "prompt": "Hello!"}'`,
        },
      },
    });
  } catch (error: any) {
    return NextResponse.json(
      { success: false, error: error.message || 'Failed to train custom model' },
      { status: 500 }
    );
  }
}
